#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XOXO_Droid.Resource", IsApplication=true)]

namespace XOXO_Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int banner = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cross = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int grid = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int settings_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splashscreen = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int transparentButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int xoxo = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070016
			public const int About = 2131165206;
			
			// aapt resource value: 0x7f07000a
			public const int Button1 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Button2 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int Button3 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int Button4 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Button5 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int Button6 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int Button7 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Button8 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int Button9 = 2131165202;
			
			// aapt resource value: 0x7f070017
			public const int Music = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int Play = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int Settings = 2131165205;
			
			// aapt resource value: 0x7f070009
			public const int gridView1 = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int imageView1 = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int relativeLayout1 = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int textView2 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int textView3 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textView4 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int textView5 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textView6 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int textView7 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int textView8 = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Game = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int menu = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
